name: Compile

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          python -m pip install -r scripts/requirements.txt
          scripts/build.py

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/*
          name: Release ${{ github.ref_name }}
          body: |
            Released by: ${{ github.actor }}
            Triggered from: ${{ github.event_name }}

